definition:
  title: List Limacharlie tags and sensors
  description: |
    Given an organization ID, list all tags and sensors in the organization
    Requires secret named `limacharlie` with keys `LIMACHARLIE_API_SECRET` and `LIMACHARLIE_OID`
  entrypoint:
    ref: list_tags
  variables:
    api_url: https://api.limacharlie.io/v1
    jwt_url: https://jwt.limacharlie.io
    token_response_key: token
  returns:
    tags: ${{ ACTIONS.list_tags.result.tags }}
    sensors: ${{ ACTIONS.list_sensors_by_tags.result.sensors }}

  actions:
    - action: core.http_request
      ref: list_tags
      args:
        url: "${{ VARS.api_url }}/tags/${{ SECRETS.limacharlie.LIMACHARLIE_OID }}"
        token_response_key: ${{ VARS.token_response_key }}
        jwt_url: "${{ VARS.jwt_url }}?oid=${{ SECRETS.limacharlie.LIMACHARLIE_OID }}&secret=${{ SECRETS.limacharlie.LIMACHARLIE_API_SECRET }}"
        method: GET

    - action: core.http_request
      ref: list_sensors
      depends_on:
        - list_tags
      args:
        url: "${{ VARS.api_url }}/sensors/${{ SECRETS.limacharlie.LIMACHARLIE_OID }}"
        token_response_key: ${{ VARS.token_response_key }}
        jwt_url: "${{ VARS.jwt_url }}?oid=${{ SECRETS.limacharlie.LIMACHARLIE_OID }}&secret=${{ SECRETS.limacharlie.LIMACHARLIE_API_SECRET }}"
        method: GET
