title: Fetch Crowdstrike alerts, suggest osquery IR queries, and open cases.
description: Pulls Crowdstrike alerts, suggests osquery IR queries for each alert, and opens cases in Tracecat.
entrypoint: pull_crowdstrike_alerts
triggers:
  - type: webhook
    ref: crowdstrike_alerts_webhook
    entrypoint: pull_crowdstrike_alerts

actions:
  # - ref: pull_crowdstrike_alerts
  #   action: integrations.crowdstrike.list_crowdstrike_alerts
  #   args:
  #     start_time: ${{ TRIGGER.start_time }}
  #     end_time: ${{ TRIGGER.end_time }}

  - ref: pull_crowdstrike_alerts
    action: integrations.faker.generate_logs_from_ecs_fields
    args:
      fields: https://github.com/elastic/integrations/raw/main/packages/crowdstrike/data_stream/alert/fields/fields.yml
      limit: 10

  - ref: reshape_alerts_into_smac
    action: core.transform.forward
    depends_on:
      - pull_crowdstrike_alerts
    for_each: ${{ for var.alert in ACTIONS.pull_crowdstrike_alerts.result }}
    args:
      # TODO: Implement the transformation logic.
      value:

  - ref: suggest_osquery_queries
    action: integrations.osquery.suggest_queries
    depends_on:
      - pull_crowdstrike_alerts
    for_each: ${{ for var.alert in ACTIONS.reshape_alerts_into_smac.result }}
    args:
      context: ${{ var.alert }}

  - ref: open_cases
    action: core.create_case
    depends_on:
      - suggest_osquery_queries
    for_each:
      - ${{ for var.alert in ACTIONS.reshape_alerts_into_smac.result }}
      - ${{ for var.query in ACTIONS.suggest_osquery_queries.result }}
    args:
      # TODO: Implement the case creation logic.
      status:
