name: Publish Images

on:
  push:
    branches: ["staging"]
    tags:
      - "*.*.*"
  pull_request:
    branches: ["staging"]

env:
  REGISTRY: ghcr.io

permissions:
  contents: read
  packages: write

jobs:
  build-and-push-api:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux/amd64
            platform_tag: amd64
          - runner: ubuntu-arm64-latest
            platform: linux/arm64
            platform_tag: arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/tracecathq/tracecat
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push
        id: build
        uses: docker/build-push-action@v6
        with:
          context: .
          platforms: ${{ matrix.platform }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true
          tags: |
            ghcr.io/tracecathq/tracecat:${{ github.sha }}-${{ matrix.platform_tag }}
            ghcr.io/tracecathq/tracecat:latest-${{ matrix.platform_tag }}

  merge-api:
    needs: build-and-push-api
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifests
        run: |
          # Create SHA manifest
          docker manifest create \
            ghcr.io/tracecathq/tracecat:${{ github.sha }} \
            --amend ghcr.io/tracecathq/tracecat:${{ github.sha }}-amd64 \
            --amend ghcr.io/tracecathq/tracecat:${{ github.sha }}-arm64
          docker manifest push ghcr.io/tracecathq/tracecat:${{ github.sha }}

          # Create latest manifest
          docker manifest create \
            ghcr.io/tracecathq/tracecat:latest \
            --amend ghcr.io/tracecathq/tracecat:latest-amd64 \
            --amend ghcr.io/tracecathq/tracecat:latest-arm64
          docker manifest push ghcr.io/tracecathq/tracecat:latest

          # If this is a PR, create PR manifest
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            docker manifest create \
              ghcr.io/tracecathq/tracecat:pr-${{ github.event.number }} \
              --amend ghcr.io/tracecathq/tracecat:${{ github.sha }}-amd64 \
              --amend ghcr.io/tracecathq/tracecat:${{ github.sha }}-arm64
            docker manifest push ghcr.io/tracecathq/tracecat:pr-${{ github.event.number }}
          fi

          # If this is a tag, create version manifest
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            docker manifest create \
              ghcr.io/tracecathq/tracecat:${VERSION} \
              --amend ghcr.io/tracecathq/tracecat:${{ github.sha }}-amd64 \
              --amend ghcr.io/tracecathq/tracecat:${{ github.sha }}-arm64
            docker manifest push ghcr.io/tracecathq/tracecat:${VERSION}
          fi

  build-and-push-ui:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - runner: ubuntu-latest
            platform: linux/amd64
            platform_tag: linux-amd64
          - runner: ubuntu-arm64-latest
            platform: linux/arm64
            platform_tag: linux-arm64
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/tracecathq/tracecat-ui
          tags: |
            type=sha
            type=ref,event=branch
            type=ref,event=pr
            type=semver,pattern={{version}}
            type=semver,pattern={{major}}.{{minor}}

      - name: Build and push by digest
        id: build
        uses: docker/build-push-action@v6
        env:
          NEXT_PUBLIC_API_URL: http://localhost:8000
          NEXT_PUBLIC_APP_ENV: production
          NEXT_PUBLIC_APP_URL: http://localhost:3000
          NEXT_SERVER_API_URL: http://localhost:8000
          NODE_ENV: production
        with:
          context: frontend
          file: frontend/Dockerfile.prod
          platforms: ${{ matrix.platform }}
          build-args: |
            NEXT_PUBLIC_API_URL=${{ env.NEXT_PUBLIC_API_URL }}
            NEXT_PUBLIC_APP_ENV=${{ env.NEXT_PUBLIC_APP_ENV }}
            NEXT_PUBLIC_APP_URL=${{ env.NEXT_PUBLIC_APP_URL }}
            NEXT_SERVER_API_URL=${{ env.NEXT_SERVER_API_URL }}
            NODE_ENV=${{ env.NODE_ENV }}
          labels: ${{ steps.meta.outputs.labels }}
          outputs: type=image,name=ghcr.io/tracecathq/tracecat-ui,push-by-digest=true,name-canonical=true,push=true
          cache-from: type=gha,scope=build-${{ matrix.platform_tag }}
          cache-to: type=gha,scope=build-${{ matrix.platform_tag }},mode=max

      - name: Export digest
        run: |
          mkdir -p /tmp/digests
          digest="${{ steps.build.outputs.digest }}"
          echo $digest > "/tmp/digests/digest.txt"

      - name: Upload digest
        uses: actions/upload-artifact@v4
        with:
          name: ui-digests-${{ matrix.platform_tag }}
          path: /tmp/digests/digest.txt
          if-no-files-found: error
          retention-days: 1

  merge-ui:
    needs: build-and-push-ui
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Container registry
        uses: docker/login-action@v3
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create and push manifests
        run: |
          # Create SHA manifest
          docker manifest create \
            ghcr.io/tracecathq/tracecat-ui:${{ github.sha }} \
            --amend ghcr.io/tracecathq/tracecat-ui:${{ github.sha }}-amd64 \
            --amend ghcr.io/tracecathq/tracecat-ui:${{ github.sha }}-arm64
          docker manifest push ghcr.io/tracecathq/tracecat-ui:${{ github.sha }}

          # Create latest manifest
          docker manifest create \
            ghcr.io/tracecathq/tracecat-ui:latest \
            --amend ghcr.io/tracecathq/tracecat-ui:latest-amd64 \
            --amend ghcr.io/tracecathq/tracecat-ui:latest-arm64
          docker manifest push ghcr.io/tracecathq/tracecat-ui:latest

          # If this is a PR, create PR manifest
          if [[ "${{ github.event_name }}" == "pull_request" ]]; then
            docker manifest create \
              ghcr.io/tracecathq/tracecat-ui:pr-${{ github.event.number }} \
              --amend ghcr.io/tracecathq/tracecat-ui:${{ github.sha }}-amd64 \
              --amend ghcr.io/tracecathq/tracecat-ui:${{ github.sha }}-arm64
            docker manifest push ghcr.io/tracecathq/tracecat-ui:pr-${{ github.event.number }}
          fi

          # If this is a tag, create version manifest
          if [[ "${{ github.ref }}" == refs/tags/* ]]; then
            VERSION=${GITHUB_REF#refs/tags/}
            docker manifest create \
              ghcr.io/tracecathq/tracecat-ui:${VERSION} \
              --amend ghcr.io/tracecathq/tracecat-ui:${{ github.sha }}-amd64 \
              --amend ghcr.io/tracecathq/tracecat-ui:${{ github.sha }}-arm64
            docker manifest push ghcr.io/tracecathq/tracecat-ui:${VERSION}
          fi
